import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { ChartWheel } from "@/components/astrology/ChartWheel";
import { PlacementsTable } from "@/components/astrology/PlacementsTable";
import { useCatalog } from "@/hooks/useCatalog";
import { createReportDownload } from "@/lib/payments/download.functions";
import type { ChartCalculation } from "@/lib/astrology/types";

export const Route = createFileRoute("/dashboard")({ component: DashboardPage });
type SavedChart = { chart_data: ChartCalculation; updated_at: string; name: string; birth_place: string };
function DashboardPage() {
  const [chart,setChart]=useState<SavedChart|null>(null); const [reports,setReports]=useState<string[]>([]); const [delivered,setDelivered]=useState<Set<string>>(new Set()); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const {catalog}=useCatalog({includeInactive:true});
  useEffect(()=>{let active=true;(async()=>{const {data:userData}=await supabase.auth.getUser();if(!userData.user){if(active)setLoading(false);return;}const db=supabase as any;const [chartRes,purchaseRes,deliveryRes]=await Promise.all([db.from("natal_charts").select("chart_data,updated_at,name,birth_place").eq("user_id",userData.user.id).maybeSingle(),db.from("report_purchases").select("report_id").eq("user_id",userData.user.id).eq("status","paid"),db.from("report_deliveries").select("report_id").eq("user_id",userData.user.id)]);if(!active)return;if(chartRes.error)setError(chartRes.error.message);setChart((chartRes.data as SavedChart|null)??null);const p=((purchaseRes.data??[])as{report_id:string}[]).map(r=>r.report_id);const d=((deliveryRes.data??[])as{report_id:string}[]).map(r=>r.report_id);setDelivered(new Set(d));setReports(Array.from(new Set([...p,...d])));setLoading(false);})();return()=>{active=false;};},[]);
  async function download(id:string){try{const result=await createReportDownload({data:{reportId:id}});window.location.assign(result.downloadUrl);}catch(e){setError((e as Error).message);}}
  if(loading)return <Shell><p className="text-muted-foreground">Loading your dashboard…</p></Shell>;
  if(!chart)return <Shell><div className="glass rounded-2xl p-10 text-center space-y-5"><h1 className="font-display text-4xl text-gradient-gold">Your Cosmic Blueprint</h1><p className="text-muted-foreground">You haven't saved a natal chart yet. Enter your birth details to calculate one with Swiss Ephemeris.</p><Link to="/" className="inline-block px-6 py-3 rounded-xl bg-gold text-primary-foreground">Calculate my chart</Link></div></Shell>;
  const c=chart.chart_data;return <Shell><div className="flex flex-wrap items-end justify-between gap-4 mb-8"><div><p className="text-xs uppercase tracking-[0.3em] text-gold">Private dashboard</p><h1 className="font-display text-4xl text-gradient-gold">{chart.name}</h1><p className="text-sm text-muted-foreground mt-1">{c.input.date} · {c.input.time} · {chart.birth_place}</p></div><Link to="/" className="text-xs uppercase tracking-wider px-4 py-2 rounded-lg border border-gold/40 text-gold">Recalculate</Link></div>{error&&<p className="mb-5 text-sm text-destructive">{error}</p>}<div className="grid lg:grid-cols-[1.2fr_1fr] gap-8 items-start"><div className="glass rounded-2xl p-6"><ChartWheel chart={c}/></div><PlacementsTable chart={c}/></div><section className="mt-10 glass rounded-2xl p-6"><h2 className="font-display text-2xl text-gradient-gold mb-4">My Reports</h2>{reports.length===0?<p className="text-sm text-muted-foreground">No purchased reports yet. Browse the report library to preview available reports.</p>:<div className="space-y-2">{reports.map(id=>{const r=catalog.find(x=>x.id===id);const ready=delivered.has(id);return <div key={id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border/40 bg-card/40 p-4"><div><div className="font-medium">{r?.title??id}</div><div className="text-xs text-muted-foreground">{ready?"Ready for private download":"Purchased — generate your report to prepare the PDF"}</div></div>{ready?<button onClick={()=>download(id)} className="px-4 py-2 rounded-lg bg-gold text-primary-foreground text-sm">Download PDF</button>:<Link to="/" className="px-4 py-2 rounded-lg border border-gold/40 text-gold text-sm">Generate</Link>}</div>})}</div>}</section></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <div className="starfield min-h-screen"><div className="max-w-6xl mx-auto px-6 py-12"><Link to="/" className="text-xs uppercase tracking-[0.3em] text-gold">← Cosmic Blueprint</Link><div className="mt-10">{children}</div></div></div>}
